parameters:
  - name: dependsOn
    displayName: Job name that needs to happen before this job
    type: string
  - name: timeoutInMinutes
    displayName: Number of minutes unit job times out
    type: number
    default: 60
  - name: notifyUsers
    displayName: Users to notify
    type: string

jobs:
  - job: approve
    displayName: Approve
    dependsOn: ${{ parameters.dependsOn }}
    pool: server
    steps:
      - task: ManualValidation@0
        inputs:
          notifyUsers: ${{ parameters.notifyUsers }}
          onTimeout: reject
          instructions: Please validate the Terraform plan
        timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
