parameters:
  - name: dockerfilePath
    type: string
    default: Dockerfile
  - name: target
    type: string
  - name: tag
    type: string
    default: $(Build.BuildNumber)

steps:
  - task: Docker@2
    displayName: Build ${{ parameters.target }} image
    inputs:
      command: build
      Dockerfile: '${{ parameters.dockerfilePath }}'
      arguments: '--target ${{ parameters.target }} -t ${{ parameters.target }}:${{ parameters.tag }}'
      addPipelineData: false
